language: generic
dist: bionic
env:
  - terraform_version="0.12.1" terraform_os_arch="linux_amd64"
install:
  - mkdir bin
  - curl -o bin/terraform.zip "https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_${terraform_os_arch}.zip"
  - unzip bin/terraform.zip -d bin
script:
  - ./bin/terraform fmt -check=true
